version: '3'

services:
  web:
    container_name: nginx
    build: 
      context: . 
      dockerfile: DockerfileNginx
    ports:
      - "80:80"
    command: nginx -g "daemon off";
    depends_on:      
      - python_api

  python_api:
    container_name: python
    build: 
      context: . 
      dockerfile: Dockerfile
    expose:
      - "8081"
    command: gunicorn -w 1 app:APP -b :8081 --reload
